- name: Install packages for minikube download
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: latest
    update_cache: yes

- name: Download minikube
  when: ansible_architecture == 'x86_64'
  become: yes
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/bin/minikube
    mode: 0755
