- name: Install base packages
  become: yes
  apt:
    name:
      - apt-transport-https
      - aspell
      - ca-certificates
      - curl
      - docker.io
      - git
      - gnupg2
      - htop
      - ipcalc
      - jq
      - ncdu
      - net-tools
      - psmisc
      - ripgrep
      - tmux
      - traceroute
      - unzip
      - wget
      - zip
    state: latest

- name: Clone dotfiles repo to the user home directory
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ ansible_user_dir }}/dotfiles"

- name: symlink dotfiles to the user home directory
  file:
    src: "{{ ansible_user_dir }}/dotfiles/{{ item }}"
    dest: "{{ ansible_user_dir }}/{{ item }}"
    state: link
    force: yes
  with_items: "{{ dotfiles }}"
