- name: Install base packages
  become: yes
  apt:
    name:
      - apt-transport-https
      - aspell
      - ca-certificates
      - curl
      - git
      - gnupg2
      - htop
      - ipcalc
      - jq
      - ncdu
      - net-tools
      - psmisc
      - ripgrep
      - tmux
      - traceroute
      - unzip
      - wget
      - zip
    state: latest

- name: Copy pull-dotfiles.sh to user's bin directory
  copy:
    src: pull-dotfiles.sh
    dest: "{{ ansible_user_dir }}/bin/"
    mode: 0755

- name: Copy aupdate to user's bin directory
  copy:
    src: aupdate
    dest: "{{ ansible_user_dir }}/bin/"
    mode: 0755

- name: Copy server-mode.sh to user's bin directory
  copy:
    src: server-mode.sh
    dest: "{{ ansible_user_dir }}/bin/"
    mode: 0755
