- name: Install packages for gcloud download
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: latest
    update_cache: yes

- name: Add Cloud SDK package source
  become: yes
  copy:
    content: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    dest: /etc/apt/sources.list.d/google-cloud-sdk.list

- name: Add apt key for Google Cloud
  become: yes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present

- name: Install the google-cloud-sdk package
  become: yes
  apt:
    update_cache: yes
    name: google-cloud-sdk
    state: latest
