- name: Install emacs from package
  become: yes
  when: emacs_package != 'source'
  apt:
    name: "{{ emacs_package }}"
    state: latest

- name: Install emacs from source
  become: yes
  when: emacs_package == 'source'
  block:
    - name: Install packages for building emacs
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - "{{ emacs_toolkit_package }}"
        - autoconf
        - build-essential
        - libgnutls28-dev
        - libncurses5-dev
        - libxpm-dev
        - libjpeg-dev
        - libtiff5-dev
        - libpng-dev
        - libgif-dev
        - libxml2-dev
        - libxft-dev
        - libfreetype6-dev
        - libjansson-dev
        - cmake
        - libtool
        - libtool-bin
        - texinfo

    - name: Cleanup existing emacs source directory
      file:
        path: "{{ emacs_source_root }}"
        state: absent

    - name: Cleanup existing emacs install directory
      file:
        path: "{{ emacs_install_root }}"
        state: absent

    - name: Create emacs source directory
      file:
        path: "{{ emacs_source_root }}"
        mode: 0777
        state: directory

    - name: Create emacs installation directory
      file:
        path: "{{ emacs_install_root }}"
        mode: 0777
        state: directory

    - name: Download emacs source files
      git:
        repo: "https://git.savannah.gnu.org/git/emacs"
        dest: "{{ emacs_source_root }}"
        depth: '1'
        version: "emacs-{{ emacs_version }}"

    - name: Run autogen on emacs
      shell:
        cmd: ./autogen.sh
        chdir: "{{ emacs_source_root }}"

    - name: Configure emacs
      shell:
        cmd: ./configure --with-native-compilation --prefix="{{ emacs_install_root }}" --with-x-toolkit="{{ emacs_toolkit }}"
        chdir: "{{ emacs_source_root }}"

    - name: Build emacs
      shell:
        cmd: make -j $(nproc)
        chdir: "{{ emacs_source_root }}"

    - name: Install emacs to installation root
      shell:
        cmd: make install
        chdir: "{{ emacs_source_root }}"

    - name: Make emacs symlinks
      file:
        src: "{{ emacs_install_root }}/bin/{{ item }}"
        dest: "/usr/bin/{{ item }}"
        state: link
      with_items:
        - emacs
        - emacsclient

    - name: Remove emacs source directory to conserve space
      file:
        path: "{{ emacs_source_root }}"
        state: absent

- name: Copy install-emacs-packages.sh to user's bin directory
  copy:
    src: install-emacs-packages.sh
    dest: "{{ ansible_user_dir }}/bin/"
    mode: 0755
